require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'app/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false